// src/mockData.js

export const mockResponseSimple = {
  algorithm: "simple",
  validation: {
    ok: true,
    errors: [],
  },
  schedule: [
    {
      examId: 0,
      groupName: "ИС-31",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 202",
      date: "2025-01-20",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 1,
      groupName: "ИС-31",
      teacherName: "Петров П.П.",
      subjectName: "Компьютерные сети",
      roomName: "Аудитория 202",
      date: "2025-01-20",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 2,
      groupName: "ИС-31",
      teacherName: "Сидоров С.С.",
      subjectName: "Базы данных",
      roomName: "Аудитория 202",
      date: "2025-01-21",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 3,
      groupName: "ИС-32",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 303",
      date: "2025-01-20",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 4,
      groupName: "ИС-32",
      teacherName: "Кузнецов К.К.",
      subjectName: "Операционные системы",
      roomName: "Аудитория 303",
      date: "2025-01-20",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 5,
      groupName: "ПО-41",
      teacherName: "Сидоров С.С.",
      subjectName: "Проектирование ПО",
      roomName: "Аудитория 202",
      date: "2025-01-21",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 6,
      groupName: "ПО-41",
      teacherName: "Фёдоров Ф.Ф.",
      subjectName: "Информационная безопасность",
      roomName: "Аудитория 303",
      date: "2025-01-21",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 12,
      groupName: "ПО-41",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 202",
      date: "2025-01-22",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 7,
      groupName: "ПО-42",
      teacherName: "Петров П.П.",
      subjectName: "Компьютерные сети",
      roomName: "Аудитория 101",
      date: "2025-01-20",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 8,
      groupName: "ПО-42",
      teacherName: "Сидоров С.С.",
      subjectName: "Базы данных",
      roomName: "Аудитория 101",
      date: "2025-01-20",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 9,
      groupName: "КС-21",
      teacherName: "Иванов И.И.",
      subjectName: "Математический анализ",
      roomName: "Аудитория 303",
      date: "2025-01-21",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 10,
      groupName: "КС-21",
      teacherName: "Кузнецов К.К.",
      subjectName: "Дискретная математика",
      roomName: "Аудитория 303",
      date: "2025-01-22",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 11,
      groupName: "ПО-41",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 202",
      date: "2025-01-22",
      startTime: "12:00",
      endTime: "14:00",
    },
  ],
};

export const mockResponseGraph = {
  algorithm: "graph",
  validation: {
    ok: true,
    errors: [],
  },
  schedule: [
    {
      examId: 0,
      groupName: "ИС-31",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 303",
      date: "2025-01-20",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 1,
      groupName: "ИС-31",
      teacherName: "Петров П.П.",
      subjectName: "Компьютерные сети",
      roomName: "Аудитория 303",
      date: "2025-01-21",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 2,
      groupName: "ИС-31",
      teacherName: "Сидоров С.С.",
      subjectName: "Базы данных",
      roomName: "Аудитория 303",
      date: "2025-01-20",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 3,
      groupName: "ИС-32",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 202",
      date: "2025-01-21",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 4,
      groupName: "ИС-32",
      teacherName: "Кузнецов К.К.",
      subjectName: "Операционные системы",
      roomName: "Аудитория 202",
      date: "2025-01-22",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 5,
      groupName: "ПО-41",
      teacherName: "Сидоров С.С.",
      subjectName: "Проектирование ПО",
      roomName: "Аудитория 303",
      date: "2025-01-21",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 6,
      groupName: "ПО-41",
      teacherName: "Фёдоров Ф.Ф.",
      subjectName: "Информационная безопасность",
      roomName: "Аудитория 303",
      date: "2025-01-22",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 12,
      groupName: "ПО-41",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 202",
      date: "2025-01-22",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 7,
      groupName: "ПО-42",
      teacherName: "Петров П.П.",
      subjectName: "Компьютерные сети",
      roomName: "Аудитория 101",
      date: "2025-01-20",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 8,
      groupName: "ПО-42",
      teacherName: "Сидоров С.С.",
      subjectName: "Базы данных",
      roomName: "Аудитория 101",
      date: "2025-01-21",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 9,
      groupName: "КС-21",
      teacherName: "Иванов И.И.",
      subjectName: "Математический анализ",
      roomName: "Аудитория 202",
      date: "2025-01-23",
      startTime: "09:00",
      endTime: "11:00",
    },
    {
      examId: 10,
      groupName: "КС-21",
      teacherName: "Кузнецов К.К.",
      subjectName: "Дискретная математика",
      roomName: "Аудитория 303",
      date: "2025-01-22",
      startTime: "12:00",
      endTime: "14:00",
    },
    {
      examId: 11,
      groupName: "ПО-41",
      teacherName: "Иванов И.И.",
      subjectName: "Алгоритмы и структуры данных",
      roomName: "Аудитория 202",
      date: "2025-01-23",
      startTime: "12:00",
      endTime: "14:00",
    },
  ],
};
